language: python
python:
  - 2.7
  - 3.5
  - 3.6

os:
  - linux

sudo: required

#cache:
#  apt: true
#  pip: true
#  directories:
#    - $PROJ_DIR

before_install:
  - ls /etc/profile.d/

install:
  - pip install -r requirements.txt
  - pip list
  - pip install .

after_install:
  - ls /etc/profile.d/

script:
  - pytest
